version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
      
  build:
    commands:
      - mvn package
      
artifacts:
  files:
    - 'webgoat-server/target/webgoat-server-v8.0.0-SNAPSHOT.jar'
  discard-paths: yes
